//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfideFactoring.SentinelWS02 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CNSDTConRapWS", Namespace="PrivadoE2Cliente")]
    [System.SerializableAttribute()]
    public partial class CNSDTConRapWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DocumentoField;
        
        private string RazonSocialField;
        
        private string FechaProcesoField;
        
        private string SemaforosField;
        
        private string ScoreField;
        
        private string NroBancosField;
        
        private string DeudaTotalField;
        
        private string VencidoBancoField;
        
        private string CalificativoField;
        
        private string Veces24mField;
        
        private double ScorePromedioField;
        
        private string SemaActualField;
        
        private string SemaPrevioField;
        
        private string SemaPeorMejorField;
        
        private string Documento2Field;
        
        private string EstDomicField;
        
        private string CondDomicField;
        
        private string DeudaTributariaField;
        
        private string DeudaLaboralField;
        
        private string DeudaImpagaField;
        
        private string DeudaProtestosField;
        
        private string DeudaSBSField;
        
        private string TarCtasField;
        
        private string RepNegField;
        
        private string TipoActvField;
        
        private string FechIniActvField;
        
        private string CodigoWSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string FechaProceso {
            get {
                return this.FechaProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaProcesoField, value) != true)) {
                    this.FechaProcesoField = value;
                    this.RaisePropertyChanged("FechaProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Semaforos {
            get {
                return this.SemaforosField;
            }
            set {
                if ((object.ReferenceEquals(this.SemaforosField, value) != true)) {
                    this.SemaforosField = value;
                    this.RaisePropertyChanged("Semaforos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreField, value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string NroBancos {
            get {
                return this.NroBancosField;
            }
            set {
                if ((object.ReferenceEquals(this.NroBancosField, value) != true)) {
                    this.NroBancosField = value;
                    this.RaisePropertyChanged("NroBancos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string DeudaTotal {
            get {
                return this.DeudaTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaTotalField, value) != true)) {
                    this.DeudaTotalField = value;
                    this.RaisePropertyChanged("DeudaTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string VencidoBanco {
            get {
                return this.VencidoBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.VencidoBancoField, value) != true)) {
                    this.VencidoBancoField = value;
                    this.RaisePropertyChanged("VencidoBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string Calificativo {
            get {
                return this.CalificativoField;
            }
            set {
                if ((object.ReferenceEquals(this.CalificativoField, value) != true)) {
                    this.CalificativoField = value;
                    this.RaisePropertyChanged("Calificativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string Veces24m {
            get {
                return this.Veces24mField;
            }
            set {
                if ((object.ReferenceEquals(this.Veces24mField, value) != true)) {
                    this.Veces24mField = value;
                    this.RaisePropertyChanged("Veces24m");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double ScorePromedio {
            get {
                return this.ScorePromedioField;
            }
            set {
                if ((this.ScorePromedioField.Equals(value) != true)) {
                    this.ScorePromedioField = value;
                    this.RaisePropertyChanged("ScorePromedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=11)]
        public string SemaActual {
            get {
                return this.SemaActualField;
            }
            set {
                if ((object.ReferenceEquals(this.SemaActualField, value) != true)) {
                    this.SemaActualField = value;
                    this.RaisePropertyChanged("SemaActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public string SemaPrevio {
            get {
                return this.SemaPrevioField;
            }
            set {
                if ((object.ReferenceEquals(this.SemaPrevioField, value) != true)) {
                    this.SemaPrevioField = value;
                    this.RaisePropertyChanged("SemaPrevio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=13)]
        public string SemaPeorMejor {
            get {
                return this.SemaPeorMejorField;
            }
            set {
                if ((object.ReferenceEquals(this.SemaPeorMejorField, value) != true)) {
                    this.SemaPeorMejorField = value;
                    this.RaisePropertyChanged("SemaPeorMejor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public string Documento2 {
            get {
                return this.Documento2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Documento2Field, value) != true)) {
                    this.Documento2Field = value;
                    this.RaisePropertyChanged("Documento2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=15)]
        public string EstDomic {
            get {
                return this.EstDomicField;
            }
            set {
                if ((object.ReferenceEquals(this.EstDomicField, value) != true)) {
                    this.EstDomicField = value;
                    this.RaisePropertyChanged("EstDomic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string CondDomic {
            get {
                return this.CondDomicField;
            }
            set {
                if ((object.ReferenceEquals(this.CondDomicField, value) != true)) {
                    this.CondDomicField = value;
                    this.RaisePropertyChanged("CondDomic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=17)]
        public string DeudaTributaria {
            get {
                return this.DeudaTributariaField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaTributariaField, value) != true)) {
                    this.DeudaTributariaField = value;
                    this.RaisePropertyChanged("DeudaTributaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=18)]
        public string DeudaLaboral {
            get {
                return this.DeudaLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaLaboralField, value) != true)) {
                    this.DeudaLaboralField = value;
                    this.RaisePropertyChanged("DeudaLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=19)]
        public string DeudaImpaga {
            get {
                return this.DeudaImpagaField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaImpagaField, value) != true)) {
                    this.DeudaImpagaField = value;
                    this.RaisePropertyChanged("DeudaImpaga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=20)]
        public string DeudaProtestos {
            get {
                return this.DeudaProtestosField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaProtestosField, value) != true)) {
                    this.DeudaProtestosField = value;
                    this.RaisePropertyChanged("DeudaProtestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=21)]
        public string DeudaSBS {
            get {
                return this.DeudaSBSField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaSBSField, value) != true)) {
                    this.DeudaSBSField = value;
                    this.RaisePropertyChanged("DeudaSBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=22)]
        public string TarCtas {
            get {
                return this.TarCtasField;
            }
            set {
                if ((object.ReferenceEquals(this.TarCtasField, value) != true)) {
                    this.TarCtasField = value;
                    this.RaisePropertyChanged("TarCtas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=23)]
        public string RepNeg {
            get {
                return this.RepNegField;
            }
            set {
                if ((object.ReferenceEquals(this.RepNegField, value) != true)) {
                    this.RepNegField = value;
                    this.RaisePropertyChanged("RepNeg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=24)]
        public string TipoActv {
            get {
                return this.TipoActvField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoActvField, value) != true)) {
                    this.TipoActvField = value;
                    this.RaisePropertyChanged("TipoActv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=25)]
        public string FechIniActv {
            get {
                return this.FechIniActvField;
            }
            set {
                if ((object.ReferenceEquals(this.FechIniActvField, value) != true)) {
                    this.FechIniActvField = value;
                    this.RaisePropertyChanged("FechIniActv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=26)]
        public string CodigoWS {
            get {
                return this.CodigoWSField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoWSField, value) != true)) {
                    this.CodigoWSField = value;
                    this.RaisePropertyChanged("CodigoWS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PrivadoE2Cliente", ConfigurationName="SentinelWS02.SentinelWS02SoapPort")]
    public interface SentinelWS02SoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (SentinelWS02.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="PrivadoE2Clienteaction/ASENTINELWS02.Execute", ReplyAction="*")]
        EfideFactoring.SentinelWS02.ExecuteResponse Execute(EfideFactoring.SentinelWS02.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PrivadoE2Clienteaction/ASENTINELWS02.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<EfideFactoring.SentinelWS02.ExecuteResponse> ExecuteAsync(EfideFactoring.SentinelWS02.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SentinelWS02.Execute", WrapperNamespace="PrivadoE2Cliente", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=2)]
        public long Servicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=3)]
        public string Tipodoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=4)]
        public string Nrodoc;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Servicio = Servicio;
            this.Tipodoc = Tipodoc;
            this.Nrodoc = Nrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SentinelWS02.ExecuteResponse", WrapperNamespace="PrivadoE2Cliente", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PrivadoE2Cliente", Order=0)]
        public EfideFactoring.SentinelWS02.CNSDTConRapWS Cnsdtconrapsms;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(EfideFactoring.SentinelWS02.CNSDTConRapWS Cnsdtconrapsms) {
            this.Cnsdtconrapsms = Cnsdtconrapsms;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SentinelWS02SoapPortChannel : EfideFactoring.SentinelWS02.SentinelWS02SoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SentinelWS02SoapPortClient : System.ServiceModel.ClientBase<EfideFactoring.SentinelWS02.SentinelWS02SoapPort>, EfideFactoring.SentinelWS02.SentinelWS02SoapPort {
        
        public SentinelWS02SoapPortClient() {
        }
        
        public SentinelWS02SoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SentinelWS02SoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SentinelWS02SoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SentinelWS02SoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EfideFactoring.SentinelWS02.ExecuteResponse EfideFactoring.SentinelWS02.SentinelWS02SoapPort.Execute(EfideFactoring.SentinelWS02.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public EfideFactoring.SentinelWS02.CNSDTConRapWS Execute(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc) {
            EfideFactoring.SentinelWS02.ExecuteRequest inValue = new EfideFactoring.SentinelWS02.ExecuteRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Servicio = Servicio;
            inValue.Tipodoc = Tipodoc;
            inValue.Nrodoc = Nrodoc;
            EfideFactoring.SentinelWS02.ExecuteResponse retVal = ((EfideFactoring.SentinelWS02.SentinelWS02SoapPort)(this)).Execute(inValue);
            return retVal.Cnsdtconrapsms;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EfideFactoring.SentinelWS02.ExecuteResponse> EfideFactoring.SentinelWS02.SentinelWS02SoapPort.ExecuteAsync(EfideFactoring.SentinelWS02.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<EfideFactoring.SentinelWS02.ExecuteResponse> ExecuteAsync(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc) {
            EfideFactoring.SentinelWS02.ExecuteRequest inValue = new EfideFactoring.SentinelWS02.ExecuteRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Servicio = Servicio;
            inValue.Tipodoc = Tipodoc;
            inValue.Nrodoc = Nrodoc;
            return ((EfideFactoring.SentinelWS02.SentinelWS02SoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
